/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */

plugins {
    java
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

version = "0.0.1"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(20))
    }
}

javafx {
    version = "20"
    modules = listOf("javafx.base")
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDir(listOf("src"))
        }
    }
}

tasks.register<JavaExec>("run_Counter") {
    group = "application"
    mainClass.set("Counter")
    classpath = sourceSets.main.get().runtimeClasspath
    standardInput = System.`in`
}